version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./sql/migrations:/docker-entrypoint-initdb.d  # Mapeia o diretório de migrações para rodar na inicialização

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      - mysql
    entrypoint: >
      /bin/sh -c "
        until mysql -h mysql -u root -proot -e 'select 1'; do
          echo 'Aguardando o banco de dados...';
          sleep 2;
        done;
        migrate -path=sql/migrations -database 'mysql://root:root@tcp(localhost:3306)/orders' -verbose up;
      "
    volumes:
      - ./sql/migrations:/migrations  # Mapeia o diretório de migrações