version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./sql/migrations:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      - mysql
    entrypoint: >
      /bin/sh -c "
        until mysql -h mysql -u root -proot -e 'select 1'; do
          echo 'Aguardando o banco de dados...';
          sleep 2;
        done;
        migrate -path=/migrations -database 'mysql://root:root@tcp(mysql:3306)/orders' -verbose up;
      "
    volumes:
      - ./sql/migrations:/migrations

  app:
    build:
      context: .  # Diretório onde está seu Dockerfile da aplicação Go
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - mysql
      - rabbitmq
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: orders
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    ports:
      - 8000:8000   # Porta do servidor web
      - 50051:50051 # Porta do servidor gRPC
      - 8080:8080   # Porta do servidor GraphQL
